<?php
        Route::controller('companies', 'CompaniesController');
                    Route::controller('paymentmethods', 'PaymentmethodsController');
                    Route::controller('site', 'SiteController');
                    Route::controller('voucher', 'VoucherController');
                    Route::controller('invoice', 'InvoiceController');
                    Route::controller('supplier', 'SupplierController');
                    Route::controller('shift', 'ShiftController');
                    Route::controller('usevoucher', 'UsevoucherController');
                    Route::controller('deposit', 'DepositController');
                    Route::controller('usedeposit', 'UsedepositController');
                    Route::controller('event', 'EventController');
                    Route::controller('sale', 'SaleController');
                    Route::controller('saleedit', 'SaleeditController');
                    Route::controller('docs', 'DocsController');
                    Route::controller('departments', 'DepartmentsController');
                    Route::controller('assign', 'AssignController');
                    Route::controller('employee', 'EmployeeController');
                    Route::controller('procedures', 'ProceduresController');
                    Route::controller('trainingtasks', 'TrainingtasksController');
                    Route::controller('trainingrecords', 'TrainingrecordsController');
                    Route::controller('trainingcategories', 'TrainingcategoriesController');
                    Route::controller('trainingsignoff', 'TrainingsignoffController');
                    Route::controller('trainingrecordsfull', 'TrainingrecordsfullController');
                    Route::controller('checkcategories', 'CheckcategoriesController');
                    Route::controller('checks', 'ChecksController');
                    Route::controller('checktimeperiods', 'ChecktimeperiodsController');
                    Route::controller('checkslog', 'CheckslogController');
                    ?>